filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - /var/ossec/logs/alerts/alerts.json
    json.keys_under_root: true
    json.add_error_key: true

output.elasticsearch:
  hosts: ["wazuh-indexer:9200"]
  protocol: http
  index: "wazuh-alerts-%{+yyyy.MM.dd}"
  allow_older_versions: true

setup.ilm.enabled: false
setup.template.enabled: false

logging.level: info
logging.to_files: false
